# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# reference: https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions/58178121#58178121
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew 
          
    - name: Build with Gradle
      run: ./gradlew build --exclude-task test
      
    - name: copy jar
      run: mkdir output && cp build/libs/*.jar output
      
    - name: upload jar.zip file
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: output
        
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2    
    
    - name: Download jar.zip file
      uses: actions/download-artifact@v2
      with:
        name: jar

    - name: set tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:          
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/teamproject-backend-test:${{ env.RELEASE_VERSION }}