name: test

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image: "example"
      tag: "dev"
      
    steps:
      - uses: actions/checkout@v2
      
      - name: change helm template
        run: |
          sed -i "s/__IMAGENAME__/${{ env.image }}/g" target.yml
          sed -i "s/__TAG__/${{ env.image }}/g" target.yml
