name: test

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image: "choisunguk/teamproject-backend-test"
      tag: "0.0.7"
      
    steps:
      - uses: actions/checkout@v2
      
      - name: change helm template
        run: |
          sed -i "s/__IMAGENAME__/'${{ env.image }}'/g" charts/values.yaml
          sed -i "s/__TAG__/'${{ env.tag }}'/g" charts/values.yaml
          cat charts/values.yaml
      
      # reference: https://github.com/helm/chart-releaser-action
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
          
      - name: Copy config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          head -1 $HOME/.kube/config
          
      - name: run kubeconfig
        run: kubectl
