name: test

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      author: "choisunguk"
      image: "teamproject-backend-test"
      tag: "0.0.7"
      namespace: "inflearn-prod"
      appname: "github-action"
      
    steps:
      - uses: actions/checkout@v2
      
      - name: change helm template
        run: |
          sed -i "s/__IMAGENAME__/${{ env.author }}\/${{ env.image }}/g" charts/values.yaml
          sed -i "s/__TAG__/'${{ env.tag }}'/g" charts/values.yaml
      
      # reference: https://github.com/helm/chart-releaser-action
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          
      - name: Copy config
        run: |
          mkdir -p $HOME/.kube
          echo ${{ secrets.KUBECONFIG }} > $HOME/.kube/config
          echo ${{ secrets.KUBERNETES_APICA }} > $HOME/.kube/ca.crt
          
      - name: Deploy app
        run: helm upgrade ${{ env.appname }} --install --namespace ${{ env.namespace }} --kube-ca-file="$HOME/.kube/ca.crt" ./charts
